### ISSUE TITLE
Error: Input string was not in a correct format. 

### ISSUE THREAD

**Issue by borjagns** [ooflet/Mi-Create#24]
When trying to compile I get the following error:

![error](https://github.com/user-attachments/assets/d0ae35d3-7da1-4ea5-90bf-cb33b5ca8efc)

"Loading D:\borjagns\Documents\EasyFace_Gen2_CompilerV46\nothing 2\nothing 2.fprj
Error: Input string was not in a correct format.
============ Errors: 1 ============
Dial name: nothing test 
Dial type: Normal 
Dial operating environment requirements:  Device Version ≥ 7.1.0 "

I attach the file in case someone manages to compile it.
If you fix something in the file please I would like to know what went wrong

[nothing-2.zip](https://github.com/user-attachments/files/16567511/nothing-2.zip)

**Comment by ooflet** [comment]
Redmi Watch 3 Active uses a different format compared to the rest of Xiaomi's wearable lineup
- There must be a background widget
- All widgets require a hex prefix in ascending order
- Widgets can use 3 different image types, RGB (where no alpha channel is drawn meaning no transparency), RGBA (with alpha) and a special format indicated with the suffix _color[AABBCC] where the image is drawn using one solid colour, only the alpha channel is actually taken into account

I'd suggest unpacking a stock watchface to see how this looks like and adapting it for your watchface.

**Comment by ooflet** [comment]
The widget "mes" is causing this error. 

Specifically, on BitmapList or the list of images, the index of each image is not a fraction, rather a number representing the month. Instead of "BitmapList="(1/12):enero.png|(2/12):febrero.png|(3/12):marzo.png|(4/12):abril.png..." it should be "BitmapList="(0):enero.png|(1):febrero.png|(2):marzo.png|(3):abril.png...". 

Attached is your project fixed up:
[nothing-2-fix.zip](https://github.com/user-attachments/files/16571397/nothing-2-fix.zip)
