### ISSUE TITLE
compiler exe source code

### ISSUE THREAD

**Issue by Chriz76** [ooflet/Mi-Create#6]
Hello, I am curious where did you get the compiler exe and if ir's source code is available. 

Thanl you!

**Comment by ooflet** [comment]
It's the compiler for EasyFace. EasyFace itself looks to be abandoned by its original creator, so m0tral now picked it up and maintains the compiler. The source code is not open for the public, however it is made C# and .NET libraries, so you could just decompile using something like dnspy or dotpeek.

**Comment by Chriz76** [comment]
Thank you. I will try that. So sad that there is no information about the APIs and formats from xiaomi. I guess that the original developer either reverse engineered it or has contact to a xiaomi developer.

**Comment by ooflet** [comment]
There is however a new file format from Xiaomi that is way more open ([362210043_Cosmic view 2_81604643913745.zip](https://github.com/ooflet/Mi-Create/files/15059293/362210043_Cosmic.view.2_81604643913745.zip)) based on xml files rather than binary files, currently only used for the Xiaomi Watch S3, which I am now planning to support. However, even with this new format Xiaomi are still not providing official software to make watchfaces with.

**Comment by Chriz76** [comment]
Thank you. I contacted the other developer. He won't release the source but it is Net so it can easily be decompiled and he allows it. He also has an unpacker with source so I could understand the format and it is very simple. 

Meanwhile I found an Android app "Mi band watch faces" that can convert my self made zip watxhfaces to bin and installs it on the phone.
